# Use the official R base image
FROM r-base:4.4.1

RUN apt-get update && apt-get install -y \
    libnetcdf-dev \
    libx11-dev \
    libcurl4-openssl-dev \
    pandoc \
    libfreetype6-dev \
    libtiff-dev \
    libwebp-dev \
    libfontconfig1-dev \
    libfribidi-dev \
    libharfbuzz-dev \
    libnetcdf-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /code

COPY dependencies.R dependencies.R

RUN R --slave --no-restore -e 'source("dependencies.R")'

COPY coordinate_plot/ coordinate_plot/
COPY extract_fb_data/ extract_fb_data/
COPY time_series/ time_series/

ENTRYPOINT ["Rscript"]
CMD ["extract_fb_data/netcdf_extract_save_fb.R"]